name: GBA

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install the latest CMake (>= 3.21)
      run: >
        sudo apt purge -y --auto-remove cmake
        && sudo apt update
        && sudo apt install -y python3-pip
        && pip install -U cmake

    - name: Remove the outdated built-in libs
      run: >
        yes | sudo dkp-pacman -R libtonc

    - name: Configure
      run: cmake --preset gba-toolchain

    - name: Build
      run: cmake --build --preset release

    - name: Copy the final ROM
      run: cmake --install cmake-build

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: GBA ROM
        path: ${{github.workspace}}/bin/gba-prog-intro.gba
